name: Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          working-dir: calculator_ui
      - name: Run Biome
        working-directory: calculator_ui
        run: biome ci .
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            .
            calculator_ui/src-tauri
      - name: Run cargo fmt & clippy & test
        run: |
          cargo fmt --check
          cargo clippy
